name: Lint project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn

      - name: Build the library
        run: yarn run build

      - name: Lint project
        run: yarn run lint
